### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by arafato** [jen20/riviera#17]
Hi--,

is this project still maintained by @jen20? Is it dead or done?

**Comment by jen20** [comment]
Hi @arafato! The project _is_ maintained and used as part of [HashiCorp Terraform](https://github.com/hashicorp/terraform) but in general I only add things to it if we find the need to use them in that project.

Sadly from a personal perspective the GitHub notification system is worthless, as I get many thousands of notifications per day via it with no obvious way to turn the alert level down. Consequently I often miss pull requests to repositories I don't look at on a daily basis - such as #16. If PRs or Issues sit unanswered for more than a couple of days here please feel free to ping via some other means!
