### ISSUE TITLE
Check resourceprovider before registering to avoid the need of privileges

### ISSUE THREAD

**Issue by superseb** [jen20/riviera#21]
This is a follow-up on https://github.com/hashicorp/terraform/issues/8824.

As suggested in the issue above, we can use this call https://docs.microsoft.com/en-us/rest/api/resources/providers#Providers_Get to check if the provider is registered without the use of higher privileges.

One approach is to incorporate this check in `RegisterResourceProvider` (https://github.com/jen20/riviera/blob/1159d86fc8144abafeb29ee7c5a3e2e85af336ba/azure/register_resource_provider.go#L17) to see if it's already registered, and only register if it is not. This won't break existing calls/functionality and helps for those that don't have the privileges. What do you think @jen20 ?

**Comment by jen20** [comment]
Looks like #22 might fix this?

**Comment by superseb** [comment]
That should do the trick
